name = "starbin"
type = "javascript"
#account_id = "6e8f81ce0e8ba25c184fa66b5fea3ac1"
workers_dev = false
zone_id = "df3e092db122d4d5ff37405c5d616b12"

routes = [
  "https://starbin.erisa.uk/raw*",
  "https://starbin.erisa.uk/documents*",
  "https://haste.erisa.uk/raw*",
  "https://haste.erisa.uk/documents*",
]

kv_namespaces = [{ binding = "STORAGE", id = "61f0941ff60b450bb6691e068c63a2c4", preview_id = "61f0941ff60b450bb6691e068c63a2c4" }]
